---
- name: gimp role
  tags:
    - gimp
  block:

  # flatpak
  - when: gimp_flatpak_state != None
    block:
    
    - name: Flatpak org.gimp.GIMP -> {{ gimp_flatpak_state }}
      become: true
      community.general.flatpak:
        name: org.gimp.GIMP
        method: "{{ gimp_flatpak_scope }}" 
        state: "{{ gimp_flatpak_state }}"
  
  # apt
  - name: Apt gimp -> {{ gimp_apt_state }}
    become: true
    ansible.builtin.apt:
      name: gimp
      state: "{{ gimp_apt_state }}"